### ISSUE TITLE
Version control issue 

### ISSUE THREAD

**Issue by jpizzati-uvl** [wbarahona/react-nicer-inputs#6]
React version was changed to "17.0.2" before updating the module version, causing conflicts with my project's React version.

**Commit where version was changed**: https://github.com/wbarahona/react-nicer-inputs/commit/803064b8e87263aeb7362e6c8c5edc6c25df56ba

**Commit where module was changed**: https://github.com/wbarahona/react-nicer-inputs/commit/313343d0b08571a1f56bdefc63b4d13c280d2772

Therefore both versions 1.14.0 and 1.14.1 are now using React version: "17.0.2".

**Comment by wbarahona** [comment]
version 1.14.2 of this package goes back to react and rect-dom@^16.13.1
